/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALexico;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GusGus
 */
public class TablaSimbolos2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form tablaSimbolos
     */
    public TablaSimbolos2() {

        initComponents();
    }
    
    public TablaSimbolos2(String cadena) {
        
        //System.out.println(crearTabla(cadena));
        ArrayList<String[]> matriz = crearTabla(cadena);
        initComponents();
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Tipo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Valor");
        modelo.addColumn("Ambito");
        for (String[] row : matriz){
            modelo.addRow(row);
        }
        
        this.Tabla.setModel(modelo);
        this.Tabla.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnRegresar5 = new javax.swing.JButton();

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        btnRegresar5.setText("Regresar");
        btnRegresar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
            .addComponent(btnRegresar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar5ActionPerformed
        // TODO add your handling code here:
//        Semantico jdesk= new Semantico();
//        jdesk.setSize(400, 500); 
//        jdesk.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRegresar5ActionPerformed

    public static ArrayList<String[]> crearTabla(String cad){
        String [] diccionario;
        cad = cad.replace("]", "");
        cad = cad.replace(" ", "");
        cad = cad.replace("[", "_");
        cad = cad.replace("\n", "°°");
        String [] lineas = cad.split("°°");
        
        ArrayList<String[]> matriz = new ArrayList<>();
        
        
        for (String l : lineas){
            diccionario = l.split(",");
            
            //if(diccionario.length == 4){
                String[] fila = new String[4];
                for (String dict : diccionario){
                    String[] key = dict.split("_");
                    //System.out.println(Arrays.toString(key));
                    if (key.length > 1){
                        
                        if(key[0].equalsIgnoreCase("pr")){
                            fila[0] = key[1];
                        }else if(key[0].equalsIgnoreCase("poo")){
                            System.out.println(key[0]);
                            fila[0] = key[1];
                        } else if(key[0].equalsIgnoreCase("id")){
                            System.out.println(key[0]);
                            fila[1] = key[1];
                        } else if(key[0].equalsIgnoreCase("num")){
                            fila[2] = key[1];
                        }else if(key[0].equalsIgnoreCase("ambito")){
                            fila[3] = key[1];
                        }
                    }
                }   
                System.out.println(Arrays.toString(fila));
                matriz.add(fila);
            //} 
        }
        
        
        
        
        return matriz;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnRegresar5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
 
}
